### ISSUE TITLE
util/build: remove BUILD script

### ISSUE THREAD

**Issue by hdonnay** [Harvey-OS/harvey#10]
One of my CLs went off the rails a bit and did this before getting reigned in, but it'll turn out better if discussed: how should util/build work if the BUILD script in the root is removed? (The implicit assumption here is that it'd be nice if it was removed.)

BUILD does some sequencing of util/build invocations, so that would have to be encoded in the json buildfiles somehow.

Should it understand barewords, like `all` or `utils` or `libs`? Should it have a default filename?

I think cramming too much more functionality into it gets away from a simple tool that can be told how to invoke the toolchain.

**Comment by Shamar** [comment]
I think we should apply the [Rule of Least Surprise](http://www.catb.org/esr/writings/taoup/html/ch11s01.html) here. 
The targets are mainly newcomers: it should be easy to build, and possibly test and run the project. 

From this point of view, facing a new build system surprised me a lot. In small OS, people expect to find a Makefile (see [Toaruos](https://github.com/klange/toaruos) or [OSv](https://github.com/cloudius-systems/osv) for example) that can use or complement alternative build tools. 
Even plan9port [provides a powerful configure script](https://github.com/9fans/plan9port/blob/master/configure)... :-)

But since we are not going to adopt a more established system, I think that having `./BUILD` or something equivalent is handy.

**Comment by Shamar** [comment]
A better BUILD should stop on error. Our current script happily proceed after an error in the kernel build.

**Comment by elbing** [comment]
Removed months ago.
