### ISSUE TITLE
nm should be replaced

### ISSUE THREAD

**Issue by gmacd** [Harvey-OS/harvey#521]
#### Expected behavior
nm should the symbol table for the given executable or object file.  It has been suggested we rewrite it in go, which seems like a good project, but it's worth fixing this first, in case the problem is caused by bugs in libmach, which seems quite possible.

#### Actual behavior
It outputs nothing.

#### Steps to reproduce
- nm /bin/drain

**Comment by elbing** [comment]
You must use at least binutils 2.26 nm, not the old native which should be removed.

**Comment by elbing** [comment]
This is wrongly focused. Old nm must be removed.

**Comment by gmacd** [comment]
What should replace it?  Should it be in apex

**Comment by elbing** [comment]
binutils package. When it would be finnished. binutils and gcc or clang won't be distributed with apex. Apex is just a lib, the fact we're keeping troff, awk and four classics with it is because they are dependent of apex, they're not in main tree and they never got package or any other distribution way or form. We need to think about how to ship packages like toolchains, python, or whatever.
Another thing is a whole system image with all of this already in it, you know, some kind of "distro".

**Comment by elbing** [comment]
#597. New port is coming.
