### ISSUE TITLE
Build with clang

### ISSUE THREAD

**Issue by sevki** [Harvey-OS/harvey#6]

**Comment by hdonnay** [comment]
So, the problem with clang currently, once you get done wrestling with compiler flags, is the "embedded structs" that `-fplan9-extensions` allows with gcc.

The C11 standard may look like it supports embedded structs, but it's actually only **anonymous** embedded structs, afaik.

Going to talk about the problem more concretely with the `Lock` type, now. Fair warning, this is all just what I understand of the problem, I could be wrong here.

There's a coccinelle patch ron has in gerrit that changes `incref` to accept the `ref` member directly instead of a `*Lock`, but this only works if the `Lock` struct can actually be embedded. I don't think it can because it's a named struct. This may be able to be fixed by making `Lock` a macro instead, that expands to the `Lock` type as an anonymous struct. This doesn't feel in keeping with the "minimal macros" goal, though.

It might be possible to change all the `Lock;` lines in structs to something like `Lock Lock;`, and then change all calls that expect a pointer to have a `Lock` embedded to instead be called with the `Lock` member, but that plan seems like lots of code touching and a bit error prone.

**Comment by aki5** [comment]
I hear you. We have been discussing alternatives in private, but now that
you brought it up it's probably time we try to figure this out.

I think one of the issues we have is that we don't really even trust that
the -fplan9-extensions gets the generated code always right. This may or
may not be a real problem, as harvey has had so many problems and blaming a
weird flag is an easy target.

But either way I think we have consensus that code relying on that flag
needs to change.

I suggested recently that we'd move to per-struct locking functions for the
common cases (ie. lock(), reflock(), etc..), to keep type checking and some
sanity in the indirection. In a lot of the cases, a lock for a struct is a
lock of the ref of the struct, which means a lot of the current lock(thing)
stuff would change into a lock(&thing->ref.lk), but there are quite a few
of them.

Ron said he may have a better idea. Anyway, I think there is no way around
the fact that this is going to touch a lot of places.

**Comment by sevki** [comment]
@rminnich is this almost complete?

**Comment by rminnich** [comment]
Acid still won't build but it is not built by default. I think we could credibly claim this is done. There is still a lingering bug in vmware: ipconfig loses dhcp responses when it's built with clang. I've isolated it to ipconfig by building ONLY ipconfig with gcc and observing that dhcp packets are not lost in that case.

So we could file per-command bugs when there are issues with building with clang and close this bug?

**Comment by sevki** [comment]
I think that would be the best, going to do some housekeeping and close some outstanding issues.
