### ISSUE TITLE
run Coverity on travis builds

### ISSUE THREAD

**Issue by sevki** [Harvey-OS/harvey#8]

**Comment by Shamar** [comment]
Coverity establishes a [limit on the number of weekly builds per project](https://scan.coverity.com/faq#frequency). Moreover [they do not allow forks to have their own reports](https://github.com/neovim/neovim/issues/1621#issuecomment-69255409).

For this reason we have to create a `coverity_scan` branch in our organizational repository, so that Harvey-OS members can push a few commits to it when they want to update the Coverity report.
With our current code size we can run up to 8 build per week.

To automate the submission I had to modify util/build so that it uses a shell to invoke all commands.
Indeed, it turns out that Coverity Scan needs a shell to invoke the compiler tools, so that it can intercept exec(2) from a dynamically linked library (via `$LD_PRELOAD`).

I'm going to submit a CL later this day with the relevant changes to .travis.yml (and util/build) but [I need the secure token to put at line 13](https://github.com/Shamar/harvey/blob/d0bc42edd89930cd902baeb0364737d8f08da0cd/.travis.yml#L13) (the project administrators should be able to find it at https://scan.coverity.com/projects/elbing-harvey/builds/new?tab=travis_ci).
It's an encrypted token designed to be publicly visible, so there's no problem to put it in our build.

Let me know the [`notification_email`](https://github.com/Shamar/harvey/blob/d0bc42edd89930cd902baeb0364737d8f08da0cd/.travis.yml#L28) to use.

/cc @elbing @fuchicar @0intro @rminnich @floren @aki5 .

**Comment by 0intro** [comment]
I've just set you as "Maintainer/Owner" on Coverity,
so you should be able to link Coverity with Travis CI.

**Comment by Shamar** [comment]
I have to related questions:

1. I've noticed that in my own (unconfigured) private fork, Coverity analyzes 466,619 lines, but in [elbing/harvey](https://scan.coverity.com/projects/elbing-harvey?tab=overview) it count only 216,890 lines: which components are configured to be ignored?
2. we have registered *elbing/harvey* repo, are we going to use it for Coverity?

If not, I'm afraid @elbing has to create a new project in Coverity for Harvey-OS and [comunicate them that the Harvey-OS/harvey is the correct one to link](https://communities.coverity.com/thread/3387).

**Comment by Shamar** [comment]
@0intro thanks! 

Would you mind to create and push a new branch named `coverity_scan` so that I can target the CL there?

**Comment by 0intro** [comment]
1. I don't really know. There is no ignored components in the Coverity configuration.
2. The URL in Coverity has been changed to https://github.com/Harvey-OS/harvey,
but I don't think there is any way to change the project name.

**Comment by 0intro** [comment]
I've just pushed a `coverity_scan` branch.

**Comment by Shamar** [comment]
Turns out that, to see the security token, I need to be added to the Harvey-OS organization, since Coverity checks that my account on travis-ci.org can access the repository. It complains that:

>  The repository is not yet known by Travis CI. Please sync your repository list on the Travis CI service, enable it for sync, and return to this page for configuration details. 

So it's easier that an admin that is signed on Coverity, Travis CI and is part of the Harvey-OS organization, write here the token (that should be visible at https://scan.coverity.com/projects/elbing-harvey/builds/new?tab=travis_ci after login).

In the meantime, I'll send a CL to master with the modifications to build.go so that you can begin it's review. When build.go will be merged, we will only need to tweek .travis.yml.

/cc @elbing @fuchicar @0intro @rminnich @floren @aki5

**Comment by 0intro** [comment]
I've just invited you to the Harvey-OS organization, so you should be able to set up Travis CI.

**Comment by Shamar** [comment]
CL sent. It's based on `master` branch, so that we can verify it build everything **without** running Coverity's tools. After that every push to `coverity_scan` branch will trigger the scan (a single compilation via GCC 4.8 is enough, thus the others are disabled in that branch)..

**Comment by Shamar** [comment]
Remember: build.go by itself do not preserve the `$LD_PRELOAD` tricks that Coverity use. 
Thus, whenever `$LD_PRELOAD` is defined, we pipe each command to a shell.
